repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: debug-statements
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.12.4
    hooks:
      # Run the linter (check-only for CI)
      - id: ruff
        files: ^(custom_components)/.+\.py$
      # Run the formatter (check-only for CI)
      - id: ruff-format
        args: [--check]
        files: ^(custom_components)/.+\.py$
