repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: debug-statements
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
          - --line-length=88
        files: ^(custom_components)/.+\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.7.0
          - pydocstyle==6.3.0
        files: ^(custom_components)/.+\.py$
        # Use the setup.cfg for configuration

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black
          - --line-length=88
        files: ^(custom_components)/.+\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        files: ^(custom_components)/.+\.py$
        args:
          - --config-file=.mypy.ini
        additional_dependencies:
          - types-requests
          - types-setuptools
