name: Bug Report
description: Report a bug or issue with the Vacasa integration
title: "[Bug] "
labels: [bug, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us resolve the issue quickly.

  - type: checkboxes
    id: checklist
    attributes:
      label: Prerequisites
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues and this bug has not been reported before
          required: true
        - label: I have updated to the latest version of the integration
          required: true
        - label: I have restarted Home Assistant after updating
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
      placeholder: A clear description of what you expected to happen
    validations:
      required: true

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      description: Which version of Home Assistant are you running?
      placeholder: e.g. 2025.1.0
    validations:
      required: true

  - type: input
    id: integration-version
    attributes:
      label: Integration Version
      description: Which version of the Vacasa integration are you using?
      placeholder: e.g. 1.2.0
    validations:
      required: true

  - type: dropdown
    id: installation-method
    attributes:
      label: Installation Method
      description: How did you install the integration?
      options:
        - HACS
        - Manual
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: |
        Please provide relevant configuration details (remove sensitive information like passwords!)
      placeholder: |
        ```yaml
        # Your configuration here (remove passwords/tokens)
        ```
      render: yaml

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: |
        Please provide relevant log entries. Enable debug logging first:
        ```yaml
        logger:
          default: info
          logs:
            custom_components.vacasa: debug
        ```
      placeholder: |
        ```
        Paste your log output here (remove any sensitive information)
        ```
      render: shell

  - type: textarea
    id: entities
    attributes:
      label: Affected Entities
      description: List the entities that are affected by this bug
      placeholder: |
        - calendar.vacasa_property_name
        - binary_sensor.vacasa_property_name_occupancy
        - sensor.vacasa_property_name_rating

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, error messages, network issues, etc.

  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      description: Please select all that apply
      options:
        - label: Home Assistant OS
        - label: Home Assistant Container
        - label: Home Assistant Core
        - label: Home Assistant Supervised
        - label: Running in Docker
        - label: Running on Raspberry Pi
        - label: Running on other ARM device
        - label: Running on x86/x64 system
