refresh_data:
  name: Refresh Data
  description: Refresh all Vacasa data including calendars, sensors, and property information immediately.
  target:
    entity:
      integration: vacasa

clear_cache:
  name: Clear Cache
  description: Clear cached data and authentication tokens.
