name: Validate with hassfest

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["*"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Check with hassfest
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Run hassfest"
        uses: "home-assistant/actions/hassfest@master"
