name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., v1.2.3)"
        required: true
        type: string

jobs:
  validate-release:
    runs-on: ubuntu-latest
    name: Validate Release
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant
          pip install -r requirements.txt

      - name: Validate version consistency
        run: |
          python -c "
          import json
          import sys

          # Get version from tag or input
          version = '${{ github.event.inputs.version }}' or '${{ github.ref_name }}'
          version = version.lstrip('v')

          # Check manifest version
          with open('custom_components/vacasa/manifest.json', 'r') as f:
              manifest = json.load(f)

          manifest_version = manifest.get('version', '')

          if manifest_version != version:
              print(f'Version mismatch: tag/input={version}, manifest={manifest_version}')
              sys.exit(1)

          # Check VERSION file if it exists
          try:
              with open('VERSION', 'r') as f:
                  file_version = f.read().strip()
              if file_version != version:
                  print(f'Version mismatch: tag/input={version}, VERSION file={file_version}')
                  sys.exit(1)
          except FileNotFoundError:
              pass

          print(f'Version validation passed: {version}')
          "

      - name: Validate HACS requirements
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands

  create-release:
    runs-on: ubuntu-latest
    name: Create Release
    needs: validate-release
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Get version
        id: version
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if [ -z "$VERSION" ]; then
            VERSION="${{ github.ref_name }}"
          fi
          VERSION=$(echo $VERSION | sed 's/^v//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          python -c "
          import json
          import subprocess
          import sys

          # Try to get changelog from CHANGELOG.md
          changelog_content = ''
          try:
              with open('CHANGELOG.md', 'r') as f:
                  content = f.read()

              # Extract section for current version
              version = '${{ steps.version.outputs.version }}'
              lines = content.split('\n')
              in_version_section = False
              for line in lines:
                  if line.startswith('## ') and version in line:
                      in_version_section = True
                      continue
                  elif line.startswith('## ') and in_version_section:
                      break
                  elif in_version_section:
                      changelog_content += line + '\n'
          except FileNotFoundError:
              pass

          # If no changelog found, generate from git commits
          if not changelog_content.strip():
              try:
                  # Get commits since last tag
                  result = subprocess.run(
                      ['git', 'log', '--oneline', '--pretty=format:- %s', 'HEAD...HEAD~10'],
                      capture_output=True, text=True
                  )
                  if result.returncode == 0:
                      changelog_content = result.stdout
              except Exception:
                  changelog_content = 'See commit history for changes.'

          # Save changelog to file
          with open('release_notes.txt', 'w') as f:
              f.write(changelog_content)

          print(f'Generated changelog for version ${{ steps.version.outputs.version }}')
          "

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          bodyFile: release_notes.txt
          draft: false
          prerelease: false
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release archive
        run: |
          mkdir -p release/custom_components
          cp -r custom_components/vacasa release/custom_components/
          cd release
          zip -r ../vacasa-${{ steps.version.outputs.version }}.zip .
          cd ..

      - name: Upload release archive
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.tag }}
          artifacts: "vacasa-${{ steps.version.outputs.version }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

  notify-hacs:
    runs-on: ubuntu-latest
    name: Notify HACS
    needs: create-release
    if: success()
    steps:
      - name: Wait for release
        run: sleep 30

      - name: Notify users
        uses: actions/github-script@v7
        with:
          script: |
            const version = '${{ steps.version.outputs.version }}';
            const body = `
            ## 🎉 New Release Available: v${version}

            A new version of the Vacasa integration has been released!

            **Installation via HACS:**
            1. Go to HACS > Integrations
            2. Find "Vacasa" in your installed integrations
            3. Click "Update" when available

            **Manual Installation:**
            1. Download the \`vacasa-${version}.zip\` from the [releases page](https://github.com/${{ github.repository }}/releases/latest)
            2. Extract to your \`custom_components\` directory
            3. Restart Home Assistant

            **What's New:**
            Check the [release notes](https://github.com/${{ github.repository }}/releases/tag/v${version}) for detailed changes.

            **Need Help?**
            - [Documentation](https://github.com/${{ github.repository }}/blob/main/README.md)
            - [Report Issues](https://github.com/${{ github.repository }}/issues)
            - [Discussions](https://github.com/${{ github.repository }}/discussions)
            `;

            // This could be used to create a discussion post about the release
            console.log('Release notification prepared');

  update-version-file:
    runs-on: ubuntu-latest
    name: Update Version File
    needs: create-release
    if: success() && github.event_name == 'workflow_dispatch'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update VERSION file
        run: |
          VERSION="${{ github.event.inputs.version }}"
          VERSION=$(echo $VERSION | sed 's/^v//')
          echo "$VERSION" > VERSION

          # Update manifest.json version
          python -c "
          import json

          with open('custom_components/vacasa/manifest.json', 'r') as f:
              manifest = json.load(f)

          manifest['version'] = '$VERSION'

          with open('custom_components/vacasa/manifest.json', 'w') as f:
              json.dump(manifest, f, indent=2)
          "

      - name: Commit version updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add VERSION custom_components/vacasa/manifest.json
          git commit -m "chore: update version to ${{ github.event.inputs.version }}" || exit 0
          git push
