name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Download repo
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          
      - uses: actions/cache@v4
        name: Cache pip dependencies
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Validate
        run: |
          pre-commit run --all-files
          pytest
          
      - name: Create zip file
        run: |
          cd custom_components/vacasa
          zip -r ../../vacasa.zip .
          
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: vacasa.zip
          asset_name: vacasa.zip
          tag: ${{ github.ref }}
          overwrite: true
