name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        name: Download repo
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - uses: actions/cache@v4
        name: Cache pip dependencies
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate
        run: |
          pre-commit run --all-files

      - name: Create zip file
        run: |
          cd custom_components/vacasa
          zip -r ../../vacasa.zip .

      - name: Upload zip to release
        uses: softprops/upload-release-action@v2.0.8
        with:
          files: vacasa.zip
          token: ${{ secrets.GITHUB_TOKEN }}
